Inflight I/O: Make structs and members public
rust-vmm/vhost pull request #54
Opened 2021-07-08 17:34 UTC by harshanavkis

The queue region and descriptor state structs introduced in the previous commits need to be public to be used by other crates.

2021-07-09 00:58 UTC, jiangliu commented on src/vhost_user/message.rs
> +}
it would be better to move current implementation into default(), and let new() call default().

2021-07-09 08:08 UTC, harshanavkis commented
@jiangliu I have addressed your comments in the new set of commits.

2021-07-09 08:08 UTC, harshanavkis commented
@jiangliu I have addressed your comments in the new set of commits.

2021-07-09 10:36 UTC, slp approved these changes

2021-07-20 12:33 UTC, stefano-garzarella submitted a review, later dismissed

2021-07-20 15:53 UTC, slp commented
@jiangliu @eryugey @sboeuf PTAL

2021-07-20 16:19 UTC, eryugey submitted a review, later dismissed

2021-07-21 07:45 UTC, sboeuf requested changes

2021-07-21 08:36 UTC, sboeuf approved these changes

2021-07-21 08:43 UTC, slp approved these changes

2021-07-21 08:43 UTC, merged