vhost_net: implement vhost_net backend
rust-vmm/vhost pull request #92
Opened 2021-10-08 06:48 UTC by Cordius

2021-10-14 10:13 UTC, stefano-garzarella requested changes
This PR LGTM, I just left a couple of comments.

Just for curiosity, why did you close #91?

2021-10-14 10:13 UTC, stefano-garzarella commented on src/vhost_kern/net.rs
> +impl<AS: GuestAddressSpace> PartialEq for Net<AS> {
Is this needed?

2021-10-14 10:13 UTC, stefano-garzarella commented on src/vhost_kern/net.rs
> +    fn test_net_ioctls() {
I'd like to add some test of `set_backend()`, I mean something like this:

```patch
diff --git a/src/vhost_kern/net.rs b/src/vhost_kern/net.rs
index f75deec..9beffdc 100644
--- a/src/vhost_kern/net.rs
+++ b/src/vhost_kern/net.rs
@@ -122,6 +122,11 @@ mod tests {
     fn test_net_ioctls() {
         let m = GuestMemoryMmap::<()>::from_ranges(&[(GuestAddress(0), 0x10_0000)]).unwrap();
         let net = Net::new(&m).unwrap();
+        let null_backend = OpenOptions::new()
+            .read(true)
+            .write(true)
+            .open("/dev/null")
+            .unwrap();
 
         let features = net.get_features().unwrap();
         net.set_features(features).unwrap();
@@ -170,5 +175,8 @@ mod tests {
         net.set_vring_kick(0, &eventfd).unwrap();
         net.set_vring_err(0, &eventfd).unwrap();
         assert_eq!(net.get_vring_base(0).unwrap(), 1);
+
+        net.set_backend(0, Some(&null_backend)).unwrap_err();
+        net.set_backend(0, None).unwrap();
     }
 }
```

2021-10-15 07:21 UTC, Cordius commented on src/vhost_kern/net.rs
> +impl<AS: GuestAddressSpace> PartialEq for Net<AS> {
I will remove it.

2021-10-28 07:07 UTC, stefano-garzarella submitted a review, later dismissed

2021-11-25 15:46 UTC, jiangliu commented
Could you please help to rebase this PR? It would be great to include it in v0.3.

2021-11-29 03:56 UTC, Cordius commented
> Could you please help to rebase this PR? It would be great to include it in v0.3.

Done

2021-11-29 06:06 UTC, jiangliu approved these changes

2021-11-29 08:51 UTC, stefano-garzarella approved these changes

2021-11-29 08:52 UTC, merged